### ISSUE TITLE
"paths" & "base-paths" ignored in defaults.yaml

### ISSUE THREAD

**Issue by HighPriest** [colcon/colcon-core#438]
```yaml
{
  "base-paths": "src/*/py"
  "paths": "src/*/py"
  "": {
    "base-paths": "src/*/py"
    "paths": "src/*/py"
  }
  "build": {
    "paths": "src/*/py"
    "symlink-install": true
    "cmake-args": "-DCMAKE_BUILD_TYPE=Debug"
  }
  "list": {
    "base-paths": "src/*/py"
    "paths": "src/*/py"
  }
}
```

None of the "paths" or "base-paths" verbs are respected by Colcon.  
`colcon list --paths-only --paths src/* src/*/py` shows expected output  
`colcon list --paths-only` does not

**Comment by christophebedard** [comment]
What about this?

```yaml
{
  "build": {
    "paths": ["src/*/py"]
  }
}
```

https://colcon.readthedocs.io/en/released/user/configuration.html#values-for-command-line-arguments

**Comment by HighPriest** [comment]
Good find, but this is not it.
```yaml
{
  "build": {
    "symlink-install": true
    "cmake-args": "-DCMAKE_BUILD_TYPE=Debug"
    "paths": ["src/*/py", "src/*"]
  }
}
```
Doesn't work.

It's parsed as YAML, so there is no need for commas.
