### ISSUE TITLE
Impossible to pass --symlink-install=false on command line to suppress a true in defaults.yaml

### ISSUE THREAD

**Issue by rsarrazin2** [colcon/colcon-core#681]
Here is my defaults.yaml file that is checked in the repository to allow for a quick build (i.e. with symlinks) on user side.
```yaml
build:
  symlink-install: true
  cmake-args:
    - "-DCMAKE_BUILD_TYPE=Debug"
    - "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
```

In the CI pipeline, as I want to publish the install directory, I want a binary release without debug information without symlinks.

For the former I use `colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release`. How can I do the latter? I cannot add `--symlink-install=false`.

Currently I'm `sed`ing the yaml file in the CI, but maybe there's a more straightforward way.

**Comment by rsarrazin2** [comment]
I now set the `COLCON_DEFAULTS_FILE` environment variable to point to e.g. defaults-release.yaml with the following content.

```yaml
build:
  symlink-install: false
  cmake-args:
    - "-DCMAKE_BUILD_TYPE=Release"
    - "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
```

```bash
(export COLCON_DEFAULTS_FILE=/ros2-pg/defaults-release.yaml; colcon build)
```

This will be sufficient for my use case, but I leave the issue open to know whether there's a command line solution.

Note that if the pointed-to file isn't found, colcon doesn't stop on the error but goes on. Is that the intended behavior?
